// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkData.DB;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SlandoDbContext))]
    [Migration("20230521131456_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Slando_Olx.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            City = "Kyiv",
                            ContactInformation = "Contact phone : 0123987509",
                            Description = "Xiaomi Redmi Note 10 Pro 6/128Gb Onyx Gray",
                            Image = "https://scdn.comfy.ua/89fc351a-22e7-41ee-8321-f8a9356ca351/https://cdn.comfy.ua/media/catalog/product/x/i/xiaomi_redmi_note_10_pro_onyx_gray_2.png/f_auto",
                            InStock = true,
                            Price = 300.0,
                            Title = "Xiaomi Redmi Note 10 Pro"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Clothes",
                            City = "Dnipro",
                            ContactInformation = "Contact email : super123@gmail.com",
                            Description = "ФУТБОЛКА NIKE SOLE FOOD TEE BLACK DM2279-010",
                            Image = "https://werare.com.ua/image/cache/webp/catalog/i/bf/nc/d74da46b40f6d40712aaa3d0eec13019-890x1000.webp",
                            InStock = true,
                            Price = 100.2,
                            Title = "NIKE SOLE FOOD TEE BLACK"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Clothes",
                            City = "Poltava",
                            ContactInformation = "Card bank Monobank : 7777-7777-7777-7777",
                            Description = "Чоловічі джинси Boss Синій (2048)",
                            Image = "https://kasta.ua/image/1035/s3/c/d9/1fc/7563772/20909940/20909940_retouched.jpeg",
                            InStock = true,
                            Price = 200.5,
                            Title = "Jeans"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Stationery",
                            City = "Rivne",
                            ContactInformation = "Epicenter",
                            Description = "Набір ручок кулькових BIC Round Stick 8 шт. сині",
                            Image = "https://cdn.27.ua/799/13/f5/332789_9.jpeg",
                            InStock = true,
                            Price = 1.75,
                            Title = "Pens"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            City = "Mykolaiv",
                            ContactInformation = "ROZETKA",
                            Description = "Телевізор Samsung UE65AU7100UXUA",
                            Image = "https://content2.rozetka.com.ua/goods/images/big/303985217.jpg",
                            InStock = true,
                            Price = 1000.0,
                            Title = "TV Samsung"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
